function [wf_x_pc, wf_y_pc, wf_z_pc] = vortSum_gpu(rx, ...
                                                   ry, ...
                                                   rz, ...
                                                   h, ...
                                                   wp_x, ...
                                                   wp_y, ...
                                                   wp_z)

h3           = h.^3;
K            = molKernel_gpu_Gaus(rx, ry, rz, h);
wf_x_pc      = wp_x*h3 * K;
wf_y_pc      = wp_y*h3 * K;
wf_z_pc      = wp_z*h3 * K;

end % function

