function [uf_x_pc, uf_y_pc, uf_z_pc] = velSum_gpu_v2(rx, ...
                                                     ry, ...
                                                     rz, ...
                                                     hp, ...
                                                     wp_x, ...
                                                     wp_y, ...
                                                     wp_z)

hp3           = hp.^3;
% [Kx, Ky, Kz] = molKernel_gpu_none(rx, ry, rz);
[Kx, Ky, Kz] = molKernel_gpu_Gaussian(rx, ry, rz, hp);
[ux, uy, uz] = crossf(Kx, Ky, Kz, wp_x*hp3, wp_y*hp3, wp_z*hp3);
uf_x_pc      = ux;
uf_y_pc      = uy;
uf_z_pc      = uz;

end % function

